//! A SHA-256 deterministic random bit generator.
//!
//! Turns a pool of entropy into an arbitrary stream of bytes. It is written here rather
//! than in `symbian` because it is arithmetic — no platform involved, so `cargo test` can
//! exercise every property that is testable at all.
//!
//! # What this is for
//!
//! MTProto needs unpredictable bytes for the client nonce, the new nonce, the Diffie-Hellman
//! secret and the session id. A predictable DH secret is a readable session, so this is not
//! a place for a convenient `Math::Random()` cast to the right width.
//!
//! # The construction
//!
//! `HMAC-SHA-256` in counter mode, reseeded by folding fresh entropy into the key:
//!
//! ```text
//! seed(e)      key = HMAC(key, 0x00 || e)          counter unchanged
//! generate     out = HMAC(key, 0x01 || counter++)  32 bytes at a time
//! ```
//!
//! HMAC rather than a bare hash of `key || counter`, because a bare hash of a secret prefix
//! is length-extendable and HMAC is what the construction is actually specified with —
//! NIST SP 800-90A's HMAC_DRBG is the same shape. The domain separator (`0x00` for reseed,
//! `0x01` for output) means a seed can never collide with an output block, which is the bug
//! that turns a DRBG into a repeating one.
//!
//! # What it does not promise
//!
//! **Forward secrecy is bounded by the key, not by the counter.** An attacker who reads the
//! `Drbg` out of memory can reproduce every future output, and every past one back to the
//! last reseed. Reseeding regularly is what limits that window, and callers doing anything
//! long-lived should call [`Drbg::reseed`] with fresh entropy periodically rather than
//! seeding once at startup.
//!
//! **It is exactly as unpredictable as its seed.** No DRBG creates entropy. On Symbian the
//! seed comes from `shim_entropy`, whose sources are enumerated honestly in the shim rather
//! than described as random; read that list before trusting this for anything.

use crate::hmac::hmac_sha256;

/// The DRBG state. 40 bytes, no allocation, and `Clone` is deliberately not derived — two
/// copies of a DRBG produce the same stream, which is the single worst failure this type
/// can have and is worth making impossible rather than documenting.
pub struct Drbg {
    key: [u8; 32],
    counter: u64,
}

/// Domain separators, so a reseed input can never be mistaken for a counter block.
const TAG_SEED: u8 = 0x00;
const TAG_OUT: u8 = 0x01;

impl Drbg {
    /// A generator seeded from `entropy`.
    ///
    /// There is no minimum length enforced, and that is a considered omission: a caller who
    /// passes four bytes has a problem this type cannot detect and cannot fix, and a length
    /// check would imply a guarantee about longer inputs that does not exist. The shim's
    /// pool is 64 bytes; `symbian::random` is the wrapper that gets it right.
    pub fn new(entropy: &[u8]) -> Self {
        let mut d = Drbg { key: [0u8; 32], counter: 0 };
        d.reseed(entropy);
        d
    }

    /// Fold fresh entropy into the state.
    ///
    /// The old key is the HMAC key and the new entropy is the message, so the result depends
    /// on both: a reseed can only ever add uncertainty, never replace good state with bad.
    /// That direction matters — an attacker who controls the entropy source cannot use a
    /// reseed to *reset* the generator to something they know.
    pub fn reseed(&mut self, entropy: &[u8]) {
        let mut msg = [0u8; 1 + 64];
        msg[0] = TAG_SEED;
        let n = entropy.len().min(64);
        msg[1..1 + n].copy_from_slice(&entropy[..n]);
        self.key = hmac_sha256(&self.key, &msg[..1 + n]);

        // Longer pools are folded in a block at a time rather than truncated.
        let mut rest = &entropy[n..];
        while !rest.is_empty() {
            let n = rest.len().min(64);
            msg[0] = TAG_SEED;
            msg[1..1 + n].copy_from_slice(&rest[..n]);
            self.key = hmac_sha256(&self.key, &msg[..1 + n]);
            rest = &rest[n..];
        }
    }

    /// Fill `out` with generated bytes.
    pub fn fill(&mut self, out: &mut [u8]) {
        let mut block = [0u8; 9];
        block[0] = TAG_OUT;
        let mut i = 0;
        while i < out.len() {
            block[1..9].copy_from_slice(&self.counter.to_be_bytes());
            self.counter = self.counter.wrapping_add(1);
            let h = hmac_sha256(&self.key, &block);
            let n = (out.len() - i).min(32);
            out[i..i + n].copy_from_slice(&h[..n]);
            i += n;
        }
    }

    /// A `u32`, for the places that want one.
    pub fn next_u32(&mut self) -> u32 {
        let mut b = [0u8; 4];
        self.fill(&mut b);
        u32::from_be_bytes(b)
    }

    /// A `u64`. MTProto message ids and session ids are 64-bit.
    pub fn next_u64(&mut self) -> u64 {
        let mut b = [0u8; 8];
        self.fill(&mut b);
        u64::from_be_bytes(b)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec;
    use alloc::vec::Vec;

    #[test]
    fn the_same_seed_gives_the_same_stream() {
        // Determinism is the property that makes a DRBG testable at all, and it is also
        // the property that makes duplicating one a disaster — hence no Clone.
        let mut a = Drbg::new(b"seed");
        let mut b = Drbg::new(b"seed");
        let (mut x, mut y) = ([0u8; 64], [0u8; 64]);
        a.fill(&mut x);
        b.fill(&mut y);
        assert_eq!(x, y);
    }

    #[test]
    fn different_seeds_diverge_immediately() {
        let mut a = Drbg::new(b"seed-a");
        let mut b = Drbg::new(b"seed-b");
        let (mut x, mut y) = ([0u8; 32], [0u8; 32]);
        a.fill(&mut x);
        b.fill(&mut y);
        assert_ne!(x, y);
    }

    #[test]
    fn no_block_ever_repeats() {
        // The failure this catches is a counter that does not advance, which produces a
        // generator that looks random and emits one block forever. It has happened in
        // shipped code more than once.
        let mut d = Drbg::new(b"whatever");
        let mut seen: Vec<[u8; 32]> = Vec::new();
        for _ in 0..512 {
            let mut b = [0u8; 32];
            d.fill(&mut b);
            assert!(!seen.contains(&b), "a 32-byte block repeated");
            seen.push(b);
        }
    }

    #[test]
    fn output_does_not_depend_on_the_size_of_the_request() {
        // One fill of 96 bytes and three of 32 must produce the same bytes, or the stream
        // depends on how it was consumed — which makes it impossible to reason about and
        // impossible to reproduce from a log.
        let mut a = Drbg::new(b"s");
        let mut b = Drbg::new(b"s");
        let mut big = [0u8; 96];
        a.fill(&mut big);
        let mut small = [0u8; 96];
        for chunk in small.chunks_mut(32) {
            b.fill(chunk);
        }
        assert_eq!(big, small);
    }

    #[test]
    fn a_partial_block_does_not_leak_into_the_next_request() {
        // Requesting 5 bytes consumes a whole counter block; the remaining 27 must be
        // discarded rather than reused, or two requests share hash output.
        let mut d = Drbg::new(b"s");
        let mut first = [0u8; 5];
        d.fill(&mut first);
        let mut second = [0u8; 32];
        d.fill(&mut second);
        assert_ne!(&second[..5], &first[..], "the second request reused the first block");
    }

    #[test]
    fn reseeding_changes_the_stream_and_depends_on_the_old_state() {
        let mut a = Drbg::new(b"s");
        let mut b = Drbg::new(b"different");
        a.reseed(b"same-extra");
        b.reseed(b"same-extra");
        let (mut x, mut y) = ([0u8; 32], [0u8; 32]);
        a.fill(&mut x);
        b.fill(&mut y);
        // Identical entropy folded into different states must stay different: an attacker
        // who controls the entropy source cannot use a reseed to force a known state.
        assert_ne!(x, y);
    }

    #[test]
    fn a_seed_longer_than_one_block_is_all_used() {
        let long_a = vec![0xAAu8; 200];
        let mut long_b = long_a.clone();
        // Change only the last byte, which lands in the third folded block.
        *long_b.last_mut().unwrap() = 0xAB;
        let (mut a, mut b) = (Drbg::new(&long_a), Drbg::new(&long_b));
        let (mut x, mut y) = ([0u8; 32], [0u8; 32]);
        a.fill(&mut x);
        b.fill(&mut y);
        assert_ne!(x, y, "entropy past the first 64 bytes was discarded");
    }

    #[test]
    fn the_bytes_look_like_bytes() {
        // Not a randomness test — no such test exists here. It catches a generator that is
        // emitting zeros, or ASCII, or the same byte, which is what a broken one usually
        // does.
        let mut d = Drbg::new(b"s");
        let mut buf = [0u8; 4096];
        d.fill(&mut buf);
        let mut counts = [0u32; 256];
        for &b in buf.iter() {
            counts[b as usize] += 1;
        }
        let unseen = counts.iter().filter(|&&c| c == 0).count();
        assert!(unseen < 20, "{unseen} byte values never appeared in 4096 bytes");
        let ones: u32 = buf.iter().map(|b| b.count_ones()).sum();
        let expect = 4096 * 8 / 2;
        assert!(
            ones.abs_diff(expect) < 500,
            "bit balance {ones} is far from {expect}"
        );
    }
}
