[package]
name = "gpsprobe"
description = "A Symbian application"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
symbian-sys = { path = "../../crates/symbian-sys" }
symbian = { path = "../../crates/symbian" }
symbian-report = { path = "../../crates/symbian-report" }
symbian-app = { path = "../../crates/symbian-app" }
