//! Physical-keyboard layouts and dead-key composition.
//!
//! # What this crate is for
//!
//! The SDK's target handset is a **Brazilian E72**, whose keyboard is **ABNT2**, and
//! until this crate existed the SDK treated it as a US QWERTY. Three things followed
//! from that, all of them user-visible:
//!
//! 1. **No accents at all.** The accent keys on an ABNT2 keyboard are dead keys, and
//!    dead-key composition is Avkon's FEP's job. We are not part of the FEP, so `~`
//!    arrived as a non-character key code (`EKeyF21`, 0xF82A) and the letter arrived
//!    separately, and nothing joined them. `~` then `a` typed `a`. Nobody could write
//!    "não", "você" or "ção".
//! 2. **No Chr/Fn symbol layer** beyond the twelve overlaid digits, so `+` could not be
//!    typed — in an app that asks for a phone number with a country code.
//! 3. **No notion of a layout**, so there was nowhere to put the fix that would not also
//!    break the handsets we have never held.
//!
//! # Why the translation lives here and not in the shim
//!
//! The C++ shim keeps the job only it can do: it receives the `TKeyEvent` and returns a
//! `TKeyResponse`. Everything semantic — which character a key means in which case,
//! which keys are dead, what `´` plus `a` is — is plain data and plain arithmetic, and
//! putting it in a `no_std` crate with no dependencies buys two things the C++ could not:
//!
//!   * it is **testable on the host**, and a keyboard is all edge cases;
//!   * the **simulator** uses the same layout, so an accent bug is reproducible in a
//!     window instead of only on the phone.
//!
//! # Where the tables come from
//!
//! Measured, never reasoned about. `docs/device-notes.md` records three rounds of
//! on-device debugging spent on keyboard behaviour that had been deduced, and each round
//! blamed the wrong layer. So [`layout_abnt2`] is generated by `tools/mkkeymap.py` from
//! a dump of the handset's own keymap, read out of `ptiengine.dll` by
//! `examples/keydump`.
//!
//! `ptiengine` is the platform's keymap engine, the layer *underneath* the FEP — asking
//! it what a key means is not the same as letting the FEP own our text buffer, which is
//! the thing we are not doing. And it is asked exactly once, offline: the result is baked
//! into a static table, so nothing that ships imports the DLL or pays for the engine.
//!
//! # Using it
//!
//! ```
//! use symbian_keys::{Keyboard, Layout, Press, Stroke};
//!
//! let mut kb = Keyboard::new(Layout::Abnt2E72);
//! // An unmapped key falls through to the character the platform translated.
//! let e = Press { scan: 0x45, code: b'e' as u16, shift: false, func: false, ctrl: false };
//! assert_eq!(kb.translate(e), Stroke::One('e'));
//! ```

#![no_std]

pub mod compose;
pub mod layout;
pub mod layout_abnt2;

// The generated table's tests, kept out of the generated file so that regenerating it
// cannot delete them — which would happen exactly when the table changed enough to need
// them most.
#[cfg(test)]
mod tests_abnt2;

pub use compose::{compose, is_mark, ACUTE, CIRCUMFLEX, DIAERESIS, GRAVE, TILDE};
pub use layout::{Case, KeyRow, Keyboard, Layout, Press, Stroke};
